apiVersion: v1
kind: PersistentVolume
metadata:
  name: motion-nfs
  namespace: private
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  nfs:
    server: 192.168.0.41
    path: "/motion/"
  mountOptions:
    - nfsvers=4
      #  secret:
      # secretName: motion-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motion-nfs
  namespace: private
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
  volumeName: motion-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: motion-nfs-config
  namespace: private
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  nfs:
    server: 192.168.0.41
    path: "/motion-config/"
  mountOptions:
    - nfsvers=4
      #  secret:
      # secretName: motion-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: motion-nfs-config
  namespace: private
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: motion-nfs-config
---
