apiVersion: v1
kind: PersistentVolume
metadata:
  name: rego-nfs
  namespace: databases
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/rego/"
  mountOptions:
    - nfsvers=4
      #  secret:
      # secretName: rego-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rego-nfs
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 60Gi
  volumeName: rego-nfs
