apiVersion: v1
kind: Service
metadata:
  name: registry-internal-service
  namespace: databases
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  externalIPs:
    - 192.168.0.180
