# ########################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-nfs
  namespace: public
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/webserver/"
  mountOptions:
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-nfs
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: webserver-nfs
# ########################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-ian
  namespace: public
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/webserver-ian/"
  mountOptions:
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-ian
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 15Gi
  volumeName: webserver-ian
# ########################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-httpd-vhosts
  namespace: public
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/webserver-httpd/conf.d/vhosts/"
  mountOptions:
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-httpd-vhosts
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: webserver-httpd-vhosts
# ########################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-httpd-htpass
  namespace: public
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/webserver-httpd/htpasswds/"
  mountOptions:
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-httpd-htpass
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: webserver-httpd-htpass
# ########################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-letsencrypt
  namespace: public
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/webserver-letsencrypt/"
  mountOptions:
    - nfsvers=4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-letsencrypt
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Mi
  volumeName: webserver-letsencrypt
# ########################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-cams-nfs
  namespace: public
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.41
    path: "/motion/"
  mountOptions:
    - nfsvers=4
      #  secret:
      # secretName: motion-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-cams-nfs
  namespace: public
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
  volumeName: webserver-cams-nfs
