apiVersion: v1
kind: Service
metadata:
  name: webserver-internal-service
  namespace: public
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  externalIPs:
    - 192.168.0.183
