apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs
  namespace: databases
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.41
    path: "/mysql/"
  mountOptions:
    - nfsvers=4
      #  secret:
      # secretName: mysql-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: mysql-nfs
