apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: databases
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  template:
    metadata:
      labels:
        app: mariadb
        type: database
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root
                  key: password
          volumeMounts:
            - name: nfs
              mountPath: "/var/lib/mysql"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: mysql-nfs
